### ISSUE TITLE
Support for bot commands in GitHub Discussions?

### ISSUE THREAD

**Issue by spenserblack** [all-contributors/all-contributors#671] opened 2022-12-15 20:33 UTC
**Is your feature request related to a problem? Please describe.**

I had an instance where a contributor described their contribution in a GitHub discussion. Because of that, I think that it would make the most sense to write the bot command in that discussion. The [documentation](https://allcontributors.org/docs/en/bot/usage) currently only references Issues and Pull Requests, but I tried anyway to confirm and it doesn't look like a discussion comment can trigger the bot.

**Describe the solution you'd like**

I'd like comments in Discussions to be supported, too, if possible.

**Describe alternatives you've considered**

Currently, I'm waiting for that user to make a small PR that I'll use to make the bot command comment.

**Comment by tenshiAMD** [comment] 2022-12-24 11:09
Duplicate of https://github.com/all-contributors/app/issues/442.

**Closed by tenshiAMD** 2022-12-24 11:09 UTC
Labels: enhancement
