### ISSUE TITLE
can't add custom tag to .all-contributorsrc

### ISSUE THREAD

**Issue by skywinder** [all-contributors/all-contributors#447] opened 2020-10-07 05:20 UTC
hello everyone!

please help me with the custom Contribution Type!
 I can't find any documentation of what fields is required, and example from
https://allcontributors.org/docs/en/cli/configuration

I try to add
```
"types": {
    "custom": {
      "symbol": "🔭",
      "description": "A custom contribution type.",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
```
as described, and got error:
```
> all-contributors add skywinder custom
url is not defined
```
I also try to remove url from link or set additional  url field like this: but have no luck:
```
  "types": {
    "root": {
      "symbol": "🎩",
      "description": "Owner and lead of the project",
      "url": "https://vas3k.ru/",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
```

also tried this structure:
```

  "types": {
    "custom": {
      "symbol": "🎩",
      "description": "Owner and lead of the project",
      "url": "https://vas3k.ru/",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
```
same issue

 but have no luck, got error:
```
root is/are invalid contribution type(s)
```
Please, guide me how to work with custom tags.

**Comment by skywinder** [comment] 2020-10-09 16:24
@Berkmann18 is there any actions needed?

**Comment by tenshiAMD** [comment] 2022-09-08 18:32
Duplicate of https://github.com/all-contributors/all-contributors/issues/290.

**Closed by tenshiAMD** 2022-09-08 18:32 UTC
Labels: bug
